version: 0.0
os: linux

permissions:
  - object: /var/www/html/demo-app
    pattern: "**"
    mode: 755
    type:
      - directory
      - file

files:
  - source: /
    destination: /var/www/html/demo-app
    overwrite: true
    
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 30
      runas: root

